---
- name: Créer des dossiers et des fichiers
  hosts: all
  tasks:
    - name: Créer le dossier "application"
      ansible.builtin.file:
        path: /chemin/vers/application
        state: directory
      become: yes

    - name: Créer le fichier "hello.sh" dans "application"
      ansible.builtin.copy:
        content: "#!/bin/bash\necho 'Hello from application folder'"
        dest: /chemin/vers/application/hello.sh
      become: yes

    - name: Créer le dossier "image"
      ansible.builtin.file:
        path: /chemin/vers/image
        state: directory
      become: yes

    - name: Créer le fichier "hello.sh" dans "image"
      ansible.builtin.copy:
        content: "#!/bin/bash\necho 'Hello from image folder'"
        dest: /chemin/vers/image/hello.sh
      become: yes

    - name: Créer le dossier "AP"
      ansible.builtin.file:
        path: /chemin/vers/AP
        state: directory
      become: yes

    - name: Créer le fichier "hello.sh" dans "AP"
      ansible.builtin.copy:
        content: "#!/bin/bash\necho 'Hello from AP folder'"
        dest: /chemin/vers/AP/hello.sh
      become: yes
