---
- name: Afficher le nom de la machine
  hosts: all
  tasks:
    - name: Obtenir le nom de la machine
      command: hostname
      register: hostname_output

    - name: Afficher le nom de la machine
      debug:
        var: hostname_output.stdout
